### ISSUE TITLE
Utilize [pop = ] accessor instead of repool for pairwise functions

### ISSUE THREAD

**Issue by zkamvar** [dwinter/mmod#3]
In all of mmod's pairwise functions, you first split populations and then repool them for each calculation.  Using the new `[pop = ]` accessor would be advantageous as it would prevent unnecessary repooling of the data.

Example:

```R  
pair <- function(index.a, index.b){
    a <- pops[[index.a]]
    b <- pops[[index.b]]
    temp <- repool(a,b)
    # do something with temp
}
```

could be turned into:

```R
pair <- function(two.pops = c(index.a, index.b), pops){
    temp <- pops[pop = two.pops]
    # do something with temp
}
```

This way, you could pass the table of combinations to `apply`:

```R
apply(allP, 2, pair, pops)
```

**Comment by dwinter** [comment]
Hi @zkamvar  -- thanks very much for spotting this. I think there is much that could be improved in `mmod`, both with adegenet2.0 functions and with a (I hope...) better programmer than I was when I first wrote it!

I will write up and test this, but want to create you as a contributor to the package in the DESCRIPTION. Is the email address in your github profile the best one to include?

**Comment by zkamvar** [comment]
:+1: Yes, that email is the best one.
