### ISSUE TITLE
use nPop instead of length(seppop())

### ISSUE THREAD

**Issue by zkamvar** [dwinter/mmod#4]
Hi. I noticed that in pairwise_fxn, you separate the populations and take the length of the list to figure out how many you need ([these two lines](https://github.com/dwinter/mmod/blob/90bdd1817ffca5874bd7fd9c68e3facaadb4dd95/R/pairwise.R#L5-L6)). This is perhaps better done with the `nPop()` accessor:

```r
n.pops <- nPop(x)
```

Cheers,
Zhian

**Comment by dwinter** [comment]
Thanks again @zkamvar, I'm sure I had some reason to go through those extra steps at some stage.... (?). But you're right, the `nPop` accessor would be much cleaner. 

I'll make the change and wait to see if the release I just send to CRAN survives the gauntlet to see if it makes into this release or the next one.
